### ISSUE TITLE
Is there a way to deploy my code on Github to AWS CodeArtifacts via Github Actions for all commits with a "release" tag?

### ISSUE THREAD

**Issue by mohtamohit** [awsdocs/aws-artifact-user-guide#2]
I have multiple questions here:

Firstly, is there a way to deploy my code on Github to AWS Artifacts via Github Actions for all commits with a "release" tag? And then is this even a recommended workflow?

To give more context, I have already setup my repo and yarn as a build tool in githb along with usage of github actions + docker as preferred CI CD. Now after my build I want to transfer the build artifacts from my pipeline to AWS CodeArtifacts and deploy to all EC2 from there.

Am I doing the right thing? How to do it? Also, please share if there are any better approaches.

Thanks in advance!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
